"use client";

import React, { useState, useMemo } from "react";
import { useLifeStore } from "@/store/useLifeStore";
import {
  Award,
  AlertTriangle,
  TrendingDown,
  TrendingUp,
  Download,
  Calendar,
  Zap,
  DollarSign,
  Sparkles,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";

export default function JourneyReplay() {
  const store = useLifeStore();
  const [selectedMonth, setSelectedMonth] = useState(new Date());

  const year = selectedMonth.getFullYear();
  const month = selectedMonth.getMonth();
  const monthStr = String(month + 1).padStart(2, "0");
  const monthPrefix = `${year}-${monthStr}`;

  const monthLabel = selectedMonth.toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });

  // Calculate stats for Journey
  const replayData = useMemo(() => {
    // 1. Targets
    const targetKeys = Object.keys(store.dailyTargets).filter((date) =>
      date.startsWith(monthPrefix)
    );

    let achievements = 0; // target completed
    let failures = 0;     // target set but not completed

    let currentStreak = 0;
    let longestStreak = 0;

    // Check all days in month
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    for (let day = 1; day <= daysInMonth; day++) {
      const dateKey = `${year}-${monthStr}-${String(day).padStart(2, "0")}`;
      const dayTarget = store.dailyTargets[dateKey];
      if (dayTarget) {
        if (dayTarget.completed) {
          achievements++;
          currentStreak++;
          if (currentStreak > longestStreak) {
            longestStreak = currentStreak;
          }
        } else {
          failures++;
          currentStreak = 0;
        }
      } else {
        currentStreak = 0;
      }
    }

    // 2. Spending
    const monthExpenses = store.expenses.filter((exp) =>
      exp.date.startsWith(monthPrefix)
    );
    const totalSpent = monthExpenses
      .filter((e) => e.type === "expense")
      .reduce((acc, curr) => acc + curr.amount, 0);
    const totalIncome = monthExpenses
      .filter((e) => e.type === "income")
      .reduce((acc, curr) => acc + curr.amount, 0);

    // High expense categories
    const categories: Record<string, number> = {};
    monthExpenses
      .filter((e) => e.type === "expense")
      .forEach((e) => {
        categories[e.category] = (categories[e.category] || 0) + e.amount;
      });

    const topCategory = Object.entries(categories).sort(
      (a, b) => b[1] - a[1]
    )[0] || ["None", 0];

    const hasData = targetKeys.length > 0 || monthExpenses.length > 0;

    return {
      hasData,
      totalTargets: targetKeys.length,
      achievements,
      failures,
      longestStreak,
      totalSpent,
      totalIncome,
      topCategoryName: topCategory[0],
      topCategoryAmount: topCategory[1],
      daysInMonth,
    };
  }, [store.dailyTargets, store.expenses, monthPrefix, year, monthStr, month]);

  const handlePrevMonth = () => {
    setSelectedMonth(new Date(year, month - 1, 1));
  };

  const handleNextMonth = () => {
    setSelectedMonth(new Date(year, month + 1, 1));
  };

  const handleDownloadReport = () => {
    const reportText = `
========================================
         L I F E   O S   R E P O R T
========================================
Month: ${monthLabel}
----------------------------------------
PRODUCTIVITY STATUS:
- Total Targets Set: ${replayData.totalTargets}
- Achievements (Completed): ${replayData.achievements}
- Failures (Uncompleted): ${replayData.failures}
- Longest Streak: ${replayData.longestStreak} days
- Month Coverage: ${Math.round((replayData.totalTargets / replayData.daysInMonth) * 100)}%

FINANCIAL LEDGER STATS:
- Total Income: $${replayData.totalIncome}
- Total Expenses: $${replayData.totalSpent}
- Top Category: ${replayData.topCategoryName} ($${replayData.topCategoryAmount})
- Savings Rate: ${replayData.totalIncome ? Math.round(((replayData.totalIncome - replayData.totalSpent) / replayData.totalIncome) * 100) : 0}%
========================================
Generated by LifeOS - A Digital Cockpit.
    `;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `LifeOS-Journey-${monthPrefix}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col gap-6 w-full">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-white/10 pb-4 gap-4">
        <div>
          <h2 className="text-xl font-black text-white flex items-center gap-2">
            <Award className="w-5 h-5 text-indigo-400" />
            Monthly Journey Replay
          </h2>
          <p className="text-xs text-slate-400 font-semibold mt-1">
            Compile month-end consistency data and archive snapshot stats.
          </p>
        </div>

        <div className="flex items-center gap-3 bg-slate-950/30 border border-white/5 p-1 rounded-xl">
          <button
            onClick={handlePrevMonth}
            className="p-2 hover:bg-white/5 rounded-lg text-slate-400 hover:text-white transition-all"
          >
            <ChevronLeft className="w-4 h-4" />
          </button>
          <span className="font-extrabold text-xs uppercase tracking-[0.15em] text-slate-200 px-2 min-w-[120px] text-center">
            {monthLabel}
          </span>
          <button
            onClick={handleNextMonth}
            className="p-2 hover:bg-white/5 rounded-lg text-slate-400 hover:text-white transition-all"
          >
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      {!replayData.hasData ? (
        <div className="rounded-2xl border border-white/5 bg-slate-950/20 p-12 text-center flex flex-col items-center justify-center gap-4">
          <div className="w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-slate-500">
            <Calendar className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white uppercase tracking-wider">No Telemetry Recorded</h3>
            <p className="text-xs text-slate-500 font-semibold mt-1 max-w-sm mx-auto">
              We cannot compile a replay card without metrics. Check-in daily targets or transactions for {monthLabel} to unlock summary snapshots.
            </p>
          </div>
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-2xl mx-auto w-full"
        >
          {/* Replay Visual Card */}
          <div className="relative rounded-2xl border border-indigo-500/20 bg-gradient-to-b from-slate-950 via-slate-950 to-indigo-950/20 p-8 shadow-2xl overflow-hidden group">
            {/* Soft decorative glow */}
            <div className="absolute -right-20 -top-20 w-48 h-48 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none group-hover:bg-indigo-500/15 transition-all"></div>
            <div className="absolute -left-20 -bottom-20 w-48 h-48 bg-purple-500/5 rounded-full blur-3xl pointer-events-none"></div>

            {/* Card Watermark */}
            <div className="absolute right-6 top-6 flex items-center gap-1.5 opacity-20">
              <Sparkles className="w-4 h-4 text-indigo-400" />
              <span className="font-extrabold text-[10px] tracking-[0.2em] text-white uppercase">LifeOS Snapshot</span>
            </div>

            {/* Header info */}
            <div className="border-b border-white/5 pb-6">
              <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest">Performance Archive</span>
              <h3 className="text-2xl font-black text-white mt-1">{monthLabel}</h3>
              <p className="text-xs text-slate-400 font-semibold mt-1">Consistency telemetry report compiled from digital check-ins.</p>
            </div>

            {/* 2x2 Grid Stats */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 my-8">
              
              {/* Box 1: Productivity Achievements */}
              <div className="p-4 rounded-xl bg-white/3 border border-white/5 flex flex-col gap-1.5">
                <span className="text-[9px] font-black text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Award className="w-3.5 h-3.5" /> Achievements
                </span>
                <span className="text-3xl font-extrabold text-white tracking-tight">
                  {replayData.achievements} <span className="text-xs text-slate-500 font-semibold">Days Done</span>
                </span>
                <p className="text-[10px] text-slate-400 font-semibold mt-1">
                  Completed targets. Great job maintaining focus milestones!
                </p>
              </div>

              {/* Box 2: Failure telemetry */}
              <div className="p-4 rounded-xl bg-white/3 border border-white/5 flex flex-col gap-1.5">
                <span className="text-[9px] font-black text-rose-400 uppercase tracking-wider flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5" /> Unfinished Targets
                </span>
                <span className="text-3xl font-extrabold text-white tracking-tight">
                  {replayData.failures} <span className="text-xs text-slate-500 font-semibold">Days Missed</span>
                </span>
                <p className="text-[10px] text-slate-400 font-semibold mt-1">
                  Targets initiated but not completed. Focus on iterative growth.
                </p>
              </div>

              {/* Box 3: Streak telemetry */}
              <div className="p-4 rounded-xl bg-white/3 border border-white/5 flex flex-col gap-1.5">
                <span className="text-[9px] font-black text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Zap className="w-3.5 h-3.5 animate-pulse" /> Focus Streak
                </span>
                <span className="text-3xl font-extrabold text-white tracking-tight">
                  {replayData.longestStreak} <span className="text-xs text-slate-500 font-semibold">Max Days</span>
                </span>
                <p className="text-[10px] text-slate-400 font-semibold mt-1">
                  Longest consecutive daily targets completed streak this month.
                </p>
              </div>

              {/* Box 4: Financial ledger stats */}
              <div className="p-4 rounded-xl bg-white/3 border border-white/5 flex flex-col gap-1.5">
                <span className="text-[9px] font-black text-yellow-400 uppercase tracking-wider flex items-center gap-1.5">
                  <DollarSign className="w-3.5 h-3.5" /> Ledger Overhead
                </span>
                <span className="text-3xl font-extrabold text-white tracking-tight">
                  ${replayData.totalSpent.toLocaleString()}{" "}
                  <span className="text-xs text-slate-500 font-semibold">
                    Spent / Top: {replayData.topCategoryName}
                  </span>
                </span>
                <p className="text-[10px] text-slate-400 font-semibold mt-1">
                  Total month spending. Highest outlay was on {replayData.topCategoryName} (${replayData.topCategoryAmount}).
                </p>
              </div>

            </div>

            {/* Bottom Actions */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-white/5 pt-6">
              <div className="flex items-center gap-2">
                {replayData.totalSpent > replayData.totalIncome && replayData.totalIncome > 0 ? (
                  <span className="text-[10px] font-black uppercase text-rose-400 flex items-center gap-1 bg-rose-500/10 border border-rose-500/20 px-2.5 py-1 rounded-full">
                    <TrendingUp className="w-3 h-3" /> Deficit Month
                  </span>
                ) : (
                  <span className="text-[10px] font-black uppercase text-emerald-400 flex items-center gap-1 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-full">
                    <TrendingDown className="w-3 h-3" /> Financial Stability
                  </span>
                )}
                <span className="text-[10px] font-mono text-slate-500">
                  COVERAGE: {Math.round((replayData.totalTargets / replayData.daysInMonth) * 100)}%
                </span>
              </div>

              <div className="flex gap-2 w-full sm:w-auto">
                <Button
                  onClick={handleDownloadReport}
                  className="flex-1 sm:flex-none bg-indigo-500 hover:bg-indigo-600 font-bold py-5 px-4 text-xs gap-1.5 rounded-xl"
                >
                  <Download className="w-4 h-4" /> Download Report Card
                </Button>
              </div>
            </div>

          </div>
        </motion.div>
      )}
    </div>
  );
}
